### ISSUE TITLE
获取紫卡信息返回null

### ISSUE THREAD

**Issue by TheRealKamisama** [Richasy/WFA-SDK#1]
在使用本SDK获取紫卡市场中特定武器的紫卡信息时返回Null
代码如下:
![图片](https://user-images.githubusercontent.com/35005476/77331282-7922d980-6d5b-11ea-8a36-75f7857834b8.png)
https://github.com/TRKS-Team/WFBot/blob/master/TRKS.WF.QQBot/RMSearcher.cs

fiddler抓包内容如下:
![图片](https://user-images.githubusercontent.com/35005476/77331456-b5563a00-6d5b-11ea-9afc-a83f326a58ca.png)

可以判断sdk请求的数据是正确的, 到了sdk处理后返回的就是一个null
希望帮我解决下这个问题, 毕竟我没找到相关的文档关于返回null是什么情况

**Comment by Richasy** [comment]
抱歉，这个确实是我的原因。
内部实现中没有转换成正确的类型。nuget包已提交更新（1.0.6），源码也已更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheRealKamisama"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 晚上11:16
收件人:&nbsp;"Richasy/WFA-SDK"<WFA-SDK@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Richasy/WFA-SDK] 获取紫卡信息返回null (#1)





 
在使用本SDK获取紫卡市场中特定武器的紫卡信息时返回Null
 代码如下:
 
 https://github.com/TRKS-Team/WFBot/blob/master/TRKS.WF.QQBot/RMSearcher.cs
 
fiddler抓包内容如下:
 
 
可以判断sdk请求的数据是正确的, 到了sdk处理后返回的就是一个null
 希望帮我解决下这个问题, 毕竟我没找到相关的文档关于返回null是什么情况
